### ISSUE TITLE
Sonar issue Do something with the "boolean" value returned by "delete".

### ISSUE THREAD

**Issue by baubakg** [adobe/phased-testing#21]
Do something with the "boolean" value returned by "delete".

https://sonarcloud.io/project/issues?id=adobe_log-parser&issues=AXzTXIhcKyg4rf3Ruv3j&open=AXzTXIhcKyg4rf3Ruv3j

**Comment by TejuManj** [comment]
Do something with the "boolean" value returned by "delete()" getting this error , how to fix this
