### ISSUE TITLE
[Documentation] Enhance the documentation to provide with some actual examples 

### ISSUE THREAD

**Issue by krmahadevan** [adobe/phased-testing#57]
This is more of a user facing documentation enhancement request.

Would it be possible to create perhaps something like an example project which basically demonstrates this library in action so that the notion of system upgrades and what it can mean in a system is a bit clearer ?

This would add a bit more context to the end-users and help them look around their current project to see avenues wherein this can be leveraged.

For example when I hear upgrades, I can think of DB upgrades, but its not clear to me as to what sort of an upgrade would it be. Would be an upgrade on the DB system itself from version x to version y or would be an upgrade of the scheme/tables in the DB.

If its the latter, then I have seen tools such as [liquibase](https://liquibase.org/) or [flyway](https://flywaydb.org/) handle these upgrades via DB as code as a concept which gets applied when a particular service comes up.

Maybe it's just me who has not yet understood the problem domain that is being solved. But I felt that if we could please help add some realtime example demo projects which can show the following:

1. A simple upgrade being simulated.
2. Tests that use this library are basically running when the upgrade is happening (or) has finished to assert the end states, it adds a bit more context.

**Comment by baubakg** [comment]
That is a great idea. I definitely need to add an example. Should it be a separate repo or inside this one?

I should have a dedicated chapter on system upgrades/changes I think.

Regarding the upgrades, we consider them as black box. In other words phased testing does not take into consideration what the change is. It just makes sure that a scenario can continue as before if a system change happens in its process.

I will definitely come up with an example. Thanks for the suggestion.

**Comment by krmahadevan** [comment]
It can be a separate one or within this. I think that shouldn't matter as long as the documentation points a user at it. Keeping it separate would perhaps be good because you can add more types of samples and that usually will bloat the main code base. Am fine with either way. Just eager to see an example so that I can also visualise the problem statement.

**Comment by baubakg** [comment]
Most Appreciated. It will be a good idea. I'll give this some good thought. Thanks for your input :)

**Comment by baubakg** [comment]
Following this suggestion, I created a dedicated repository as a real example project:
https://github.com/baubakg/phased-test-demo
